syntax = "proto3";

package rosengine;

service RosEngine {
  rpc StreamEvents(Empty) returns (stream WorkspaceEvent);
  rpc PublishTwist(TwistCommand) returns (Empty);
}

message TwistCommand {
  string topic_name = 1;
  double linear_x = 2;
  double angular_z = 3;
}

message Empty {}

message WorkspaceEvent {
  oneof event {
    NodeStarted node_started = 1;
    NodeCrashed node_crashed = 2;
    TopicSnapshot topic_snapshot = 3;
    OdometryUpdate odometry_update = 4;
    TFUpdate tf_update = 5;
    NodeSnapshot node_snapshot = 6;
  }
  int64 timestamp_ns = 10;
}

message NodeSnapshot {
  repeated string node_names = 1;
}

message TFUpdate {
  string parent_frame = 1;
  string child_frame = 2;
  double x = 3;
  double y = 4;
  double z = 5;
  double qx = 6;
  double qy = 7;
  double qz = 8;
  double qw = 9;
}

message NodeStarted {
  string node_name = 1;
}

message NodeCrashed {
  string node_name = 1;
}

message TopicSnapshot {
  repeated Topic topics = 1;
}

message Topic {
  string name = 1;
  repeated string types = 2;
}

message OdometryUpdate {
  string topic_name = 1;
  double x = 2;
  double y = 3;
  double z = 4;
  double qx = 5;
  double qy = 6;
  double qz = 7;
  double qw = 8;
}